build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: false
                    -
                        command: './vendor/bin/phpunit --coverage-clover=./coverage.xml'
                        coverage:
                          file: ./coverage.xml
                          format: clover
filter:
    excluded_paths:
        - 'tests/*'
tools:
    php_code_coverage: true
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true